### ISSUE TITLE
OpenStack Platform 9 instance create error

### ISSUE THREAD

**Issue by vinay-patil** [fog/fog-openstack#185]
Hello,

We are facing below error while creating the instance on **platform9 OpenStack** - 

**Note:** We are able to list the images and flavors using compute object.

**OutPut:**

```
irb(main):055:0> par =  { name: 'test', image_ref: image.id, flavor_ref: flavor.id }
=> {:name=>"test", :image_ref=>"16d04dd1-e871-4511-9c2a-009df4587c60", :flavor_ref=>"1"}
irb(main):056:0> instance = compute.servers.create(par)
Excon::Error::InternalServerError: Expected([200, 202]) <=> Actual(500 InternalServerError)
excon.error.response
  :body          => "{\"computeFault\": {\"message\": \"Unexpected API Error. Please report this at http://bugs.launchpad.net/nova/ and attach the Nova API log if possible.\\n<type 'exceptions.TypeError'>\", \"code\": 500}}"
  :cookies       => [
  ]
  :headers       => {
    "Access-Control-Allow-Credentials" => "true"
    "Access-Control-Allow-Origin"      => "https://rlt.platform9.net"
    "Connection"                       => "keep-alive"
    "Content-Length"                   => "193"
    "Content-Type"                     => "application/json; charset=UTF-8"
    "Date"                             => "Sat, 03 Sep 2016 14:56:16 GMT"
    "Server"                           => "nginx/1.10.1"
    "X-Compute-Request-Id"             => "req-352b44cb-9eed-4845-a922-e975714d35e2"
  }
  :host          => "rlt.platform9.net"
  :local_address => "192.168.0.146"
  :local_port    => 58372
  :path          => "/nova/v2/e85b5c4ec6ab4cd5b93ef7ab77e97f20/servers.json"
  :port          => 443
  :reason_phrase => "Internal Server Error"
  :remote_ip     => "52.9.219.225"
  :status        => 500
  :status_line   => "HTTP/1.1 500 Internal Server Error\r\n"

	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/excon-0.52.0/lib/excon/middlewares/expects.rb:7:in `response_call'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/excon-0.52.0/lib/excon/middlewares/response_parser.rb:9:in `response_call'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/excon-0.52.0/lib/excon/connection.rb:388:in `response'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/excon-0.52.0/lib/excon/connection.rb:252:in `request'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/fog-core-1.42.0/lib/fog/core/connection.rb:81:in `request'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/fog-openstack-0.1.12/lib/fog/openstack/core.rb:81:in `request'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/fog-openstack-0.1.12/lib/fog/compute/openstack/requests/create_server.rb:81:in `create_server'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/fog-openstack-0.1.12/lib/fog/compute/openstack/models/server.rb:379:in `save'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/fog-core-1.42.0/lib/fog/core/collection.rb:51:in `create'
	from (irb):56
	from /opt/chef/embedded/bin/irb:11:in `<main>'
irb(main):057:0> ^C
irb(main):057:0> 

```

**Comment by vinay-patil** [comment]
@seanhandley @Ladas  ^ Please help on this !

**Comment by Ladas** [comment]
@vinay-patil which OpenStack version is that? I will need to see the error from the OpenStack side, e.g. find it in 'journalctl -ab -r', and search for nova, after running that fog command.
