### ISSUE TITLE
Version 0.2.0 breaks when endpoints in the catalog have a version attached to them

### ISSUE THREAD

**Issue by horazont** [fog/fog-openstack#420]
If an openstack service has the version in the identity endpoint explicitly like this:

```
| keystone       | identity        | f1a                                                                                                  |
|                |                 |   public: https://identity-f1a.cloudandheat.com:5000/v3                                              |
|                |                 | f1a                                                                                                  |
|                |                 |   internal: https://identity-f1a.cloudandheat.com:5000/v3                                            |
|                |                 | f1a                                                                                                  |
|                |                 |   admin: https://identity-f1a.cloudandheat.com:35357/v3                                              |
```

fog-openstack 0.2.0 breaks with an error like this:

```
/var/lib/gems/2.3.0/gems/excon-0.62.0/lib/excon/middlewares/expects.rb:7:in `response_call': Expected([200]) <=> Actual(404 Not Found) (Fog::Identity::OpenStack::NotFound)
excon.error.response
  :body          => "{\"error\": {\"message\": \"(https://identity-f1a.cloudandheat.com:35357/v3/v3/domains): The resource could not be found.\", \"code\": 404, \"title\": \"Not Found\"}}"
  :cookies       => [
  ]
  :headers       => {
    "Content-Length"         => "154"
    "Content-Type"           => "application/json"
    "Date"                   => "Wed, 29 Aug 2018 12:45:52 GMT"
    "Server"                 => "Apache/2.4.18 (Ubuntu)"
    "Vary"                   => "X-Auth-Token"
    "x-openstack-request-id" => "req-b3a66bcc-c961-48d4-aea8-72922b9a960c"
  }
  :host          => "identity-f1a.cloudandheat.com"
  :local_address => "172.17.0.2"
  :local_port    => 47632
  :path          => "/v3/v3/domains"
  :port          => 35357
  :reason_phrase => "Not Found"
  :remote_ip     => "185.128.119.1"
  :status        => 404
  :status_line   => "HTTP/1.1 404 Not Found\r\n"
        from /var/lib/gems/2.3.0/gems/excon-0.62.0/lib/excon/middlewares/response_parser.rb:9:in `response_call'
        from /var/lib/gems/2.3.0/gems/excon-0.62.0/lib/excon/connection.rb:414:in `response'
        from /var/lib/gems/2.3.0/gems/excon-0.62.0/lib/excon/connection.rb:263:in `request'
        from /var/lib/gems/2.3.0/gems/fog-core-1.45.0/lib/fog/core/connection.rb:81:in `request'
        from /var/lib/gems/2.3.0/gems/fog-openstack-0.2.0/lib/fog/openstack/core.rb:53:in `request'
        from /var/lib/gems/2.3.0/gems/fog-openstack-0.2.0/lib/fog/identity/openstack/v3/requests/list_domains.rb:7:in `list_domains'
        from /var/lib/gems/2.3.0/gems/fog-openstack-0.2.0/lib/fog/identity/openstack/v3/models/domains.rb:18:in `all'
        from /var/lib/gems/2.3.0/gems/fog-core-1.45.0/lib/fog/core/collection.rb:112:in `lazy_load'
        from /var/lib/gems/2.3.0/gems/fog-core-1.45.0/lib/fog/core/collection.rb:16:in `to_s'
        from test.rb:14:in `write'
        from test.rb:14:in `print'
        from test.rb:14:in `<main>'
```

Reproducer script:
```ruby
gem 'fog-core', '1.45.0'
gem 'fog-openstack', '0.2.0'

require 'fog/openstack'

conn = Fog::Identity::OpenStack.new(
  openstack_auth_url: 'https://identity.service.example',
  openstack_username: 'my-username',
  openstack_api_key: 'my-password',
  openstack_project_name: 'my-project',
  openstack_domain_id: 'default'
)

print(conn.domains)
```

Further info: [in the gitter chat](https://gitter.im/fog/fog-openstack?at=5b868b8be5b40332ab14dbd4)

**Comment by gildub** [comment]
@horazont, good on you for reporting this one quickly! 
PR #421 takes care of it. 
What makes me really happy is the fact that using the new approach for handling endpoints from 0.2.0 allows us to tackle cases of having endpoints with or without a version.
